spring.application.name=user-service

# ===============================
# Server Configuration
# ===============================

server.port=8081


# ===============================
# Eureka Client Configuration
# ===============================

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# ===============================
# PostgreSQL Database Configuration
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate Configuration
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# Import Secret Configuration
# ===============================

spring.config.import=optional:application-secret.properties

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

