spring.application.name=transaction-service

server.port=8084


spring.config.import=optional:application-secret.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/transaction_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

management.endpoints.web.exposure.include=health,info

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG





# Eureka Configuration






# Database



spring.datasource.driver-class-name=org.postgresql.Driver


# JPA










